library(MASS)
titanicgrp <- read.csv("titanicgrp.csv")
attach (titanicgrp)
lncases <-log(cases)
reslm <- glm.nb(survive ~ age + sex + factor(whichclass) + offset(lncases), data = titanicgrp)
ressum <- summary(reslm)
print (ressum)
res <- coef(reslm)
print (res)
print (exp(res))
