'''
Takes the file generated by movielens_prep, and generates another file
that has user_id tab seperated, and all non-null ratings are in the
"movieid:rating" format.
'''
import pandas as pd, re

fin = open ("%s/Downloads/movielens.csv" % os.environ['HOME'])
header = fin.readline() # skip
for j,line in enumerate(fin.readlines()):
    line = re.findall("(.*?);",line)
    id = line[0]; line = line[1:-1]
    res = [str(i)+":"+str(x) for i,x in enumerate(line) if x]
    print id + '\t' + ';'.join(res)
